name: HTTP Annotation Bundle

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suites
      run: composer test

    - name: Run code style
      run: composer cs:check
