name: HTTP Annotation Bundle

on: [push]

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Validate composer.json and composer.lock"
      run: composer validate

    - name: "Install dependencies"
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: "Run test suites"
      run: composer test

    - name: "Code style"
      run: composer cs:check
